version: '3.7'
services:  
  db:
    image: mysql
    restart: always
    ports: 
      - "3310:3306"
    environment:
      MYSQL_DATABASE: 'laravel8dbprac'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravel8dbapp'
    ports:
    - 8083:80
    volumes:
      - ./:/var/www/html